spring:
  datasource:
    url: jdbc:mysql://47.103.120.241:3306/questionnaire_investigation?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=CTT
    username: yingzhuxinxi
    password: yingzhuxinxi

swagger:
  enable: true


wechat:
  appid: wx25fd88f52c760f2d
  secret: 38ae7672ef46971830f0458514d0183e


redis:
  topic:
    personal: prod-personal
    update-report-all: update-report-all-prod

test:
  code: hand

server:
  #  ssl:
  #    key-store: classpath:top.sales.top.jks
  #    key-store-password: lgmpi1i0
  #    key-store-type: JKS
  port: 8080